package com.bank.exception;

public enum ErrorCode {
    ACCOUNT_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    INVALID_AMOUNT,
    USER_CREATION_FAILED,
    ACCOUNT_CREATION_FAILED,
    TRANSFER_FAILED,
    INVALID_ACCOUNT_TYPE,
    INVALID_CREDENTIALS
}
